<a href="https://colab.research.google.com/github/laxmipunnam/pythontrainingLab/blob/main/numpy_day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import numpy using import keyword
import numpy


In [2]:
#create 1-d array using numpy
arr=numpy.array([1,2,3,4,5,6])

In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
#check the version
print(numpy.__version__)

1.21.6


In [9]:
#can we create array using tuple
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)

#create 2-d array using 2 list
arr1=np.array([[1,2,3],[4,5,6]])
print("2-d array",arr1)

[1 2 3 4 5]
2-d array [[1 2 3]
 [4 5 6]]


In [10]:
#create 3-d array

arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[4,5,6]]])
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [4 5 6]]]


In [12]:
#check dimension of array

print("dim of arr",arr.ndim)
print("dim of arr1",arr1.ndim)
print("dim of arr3",arr3.ndim)


dim of arr 1
dim of arr1 2
dim of arr3 3


In [25]:
#indexing in array
print(arr[3])
#find index in 1-d array and 2-d array
print(arr[4])
print(arr1[1][0])
#slicing in 1-d and 2-d array
print(arr[1:3])
print(arr1[0:1])
print(arr1[1,1])

4
5
4
[2 3]
[[1 2 3]]
5


In [87]:
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [4 5 6]]]


In [35]:
print(arr3[1,1,2])

6


In [36]:
print(arr3[3,1,2])

IndexError: ignored

In [39]:
#negative indexing
print(arr1)


[[1 2 3]
 [4 5 6]]


In [41]:
print(arr1[1,-1])

6


In [42]:
#slicing
a=np.array([1,2,3,4,5,6,7])
print(arr[1:4])
print(arr[:4])
print(a[4:])
print(a[-3:-1])

[2 3 4]
[1 2 3 4]
[5 6 7]
[5 6]


In [43]:
#slicing in 2-d
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b.ndim)

2


In [44]:
b[1,1:4]

array([7, 8, 9])

In [45]:
#how to acess 8,9
b[1,2:4]

array([8, 9])

In [48]:
#access the index 1 to index 3 from both array
b[0:2,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [49]:
#shape of array
print("shape of array a:",a.shape)
print("shape of array b:",b.shape)

shape of array a: (7,)
shape of array b: (2, 5)


In [86]:
#iterate over array using loop
for x in b:
  print(x)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [51]:
#scaler elements from 2-d array using nested loop
for x in b:
  for y in x:
    print(y)

1
2
3
4
5
6
7
8
9
10


In [53]:
for x in arr3:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
4
5
6


In [88]:
#nditer
for x in np.nditer(arr3):
  print(x)
for r in np.nditer(b):
  print(r)


1
2
3
4
5
6
7
8
9
4
5
6
1
2
3
4
5
6
7
8
9
10


In [54]:
#some trignometric function
x=np.sin(np.pi/2)
print(x)


1.0


In [55]:
arr=np.array([np.pi/2,np.pi/3,np.pi/4,np.pi/5])
z=np.sin(arr)
y=np.cos(arr)
print(z)
print(y)

[1.         0.8660254  0.70710678 0.58778525]
[6.12323400e-17 5.00000000e-01 7.07106781e-01 8.09016994e-01]


In [56]:
#radian=pi/180*degree
arr=np.array([90,180,270,360])
x1=np.deg2rad(arr)
print(x1)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [57]:
arr1=np.array([np.pi/2,np.pi,1.5*np.pi,2*np.pi])
x=np.rad2deg(arr1)
print(x)

[ 90. 180. 270. 360.]


In [59]:
arr=np.around(3.145,2)
print(arr)

3.14


In [62]:
arr=np.ceil([-3.166,3.667])
print(arr)

[-3.  4.]


In [63]:
arr=np.floor([-3.166,3.667])
print(arr)

[-4.  3.]


In [64]:
arr=np.trunc([-3.166,3.667])
print(arr)

[-3.  3.]


In [65]:
arr=np.fix([-3.166,3.667])
print(arr)

[-3.  3.]


mathematical function

In [66]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
addarray=np.add(arr1,arr2)
print(addarray)

[5 7 9]


In [67]:
#it sum the values of both arr1 and arr2
addarray=np.sum([arr1,arr2])
print(addarray)

21


In [68]:
#you can sum along with axis
addarray=np.sum([arr1,arr2],axis=1)
print(addarray)

[ 6 15]


In [69]:
#you can sum along with axis
addarray=np.sum([arr1,arr2],axis=0)
print(addarray)

[5 7 9]


In [71]:
a=np.array([1,2,3,4,5,6,7])
cumsumArray=np.cumsum(a)
print(cumsumArray)

[ 1  3  6 10 15 21 28]


In [72]:
a=np.array([1,2,3,4,5,6,7])
cumprodArray=np.cumprod(a)
print(cumprodArray)

[   1    2    6   24  120  720 5040]


In [73]:
a=np.array([1,2,3,4,5,6,7])
prodArray=np.prod(a)
print(prodArray)

5040


In [77]:
#create the prod over axis=0
a=np.array([1,2,3,4,5,6,7])
prodArray=np.prod([a],axis=0)
print(prodArray)

[1 2 3 4 5 6 7]


In [76]:
#create the prod over axis=1
a=np.array([1,2,3,4,5,6,7])
prodArray=np.prod([a],axis=1)
print(prodArray)

[5040]


In [80]:
#arithmetic operation 
r1=np.array([10,11,12,13,14,15])
r2=np.array([20,21,22,23,24,25])
addA=np.add(r1,r2)
print("addition:",addA)

subA=np.subtract(r2,r1)
print("subtraction:",subA)

mulA=np.multiply(r1,r2)
print("multiply:",mulA)

divA=np.divide(r2,r1)
print("division:",divA)

addition: [30 32 34 36 38 40]
subtraction: [10 10 10 10 10 10]
multiply: [200 231 264 299 336 375]
division: [2.         1.90909091 1.83333333 1.76923077 1.71428571 1.66666667]


In [81]:
r1=np.array([1,2,3,4,5,6])
r2=np.array([0,1,2,3,4,5])
powA=np.power(r1,r2)
print("power:",powA)

power: [   1    2    9   64  625 7776]


In [82]:
r1=np.array([1,2,3,4,5,6])
r2=np.array([2,1,2,3,4,5])
remA=np.remainder(r1,r2)
print("remainder:",remA)

remainder: [1 0 1 1 1 1]


In [83]:
r1=np.array([1,2,3,4,5,6])
r2=np.array([2,1,2,3,4,5])
divmodA=np.divmod(r1,r2)
print("remainder:",divmodA)

remainder: (array([0, 2, 1, 1, 1, 1]), array([1, 0, 1, 1, 1, 1]))


In [84]:
r1=np.array([1,-2,3,-4,5,6])
absA=np.absolute(r1)
print(absA)

[1 2 3 4 5 6]


In [104]:
#statiscal function
# mean
import statistics

n= [8,5,10,12,16,13,15,19,20]
mean = statistics.mean(n)
print(mean)
# median
n= [8,5,10,12,16,13,15,19,20]
median = statistics.median(n)
print(median)
# mod
n= [9, 4, 6, 4, 5, 2, 10, 12, 1, 4, 4, 7]
mode = statistics.mode(n)
print(mode)
# stddev
stddev=statistics.stdev(n)
print(stddev)
# variance
variance=statistics.variance(n)
print(variance)


13.11111111111111
13
4
3.2844906435973886
10.787878787878787
